import { useEffect, useRef, useState, type ReactNode } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowDownLeft, ArrowUpRight, ArrowRight, Plus, Wallet, Home, CalendarDays, ArrowLeftRight, ChartNoAxesCombined, Settings, ChevronDown, MoreHorizontal, Coffee, ShoppingBag, TrainFront, ShoppingBasket, ShieldCheck, Wifi, Clapperboard, CircleCheck, X, Link2, SkipForward, Check, RotateCcw, type LucideIcon } from 'lucide-react';
import { checkSpending, occurrences, rupees, summary, type Occurrence } from '../src/lib/finance/engine';
import { document, number as n, string as s, validateData, type Document } from '../src/lib/finance/model';
import { nextPaymentPerPlan, previewName, previewToday, sampleRecords } from './data';

const money = (amount: number) => rupees(amount).replace(/\.00$/, '');
const date = (value: string) => new Date(value + 'T12:00:00').toLocaleDateString('en-IN', { day: 'numeric', month: 'short' });
const categoryIcons: Record<string, LucideIcon> = { food: ShoppingBasket, shopping: ShoppingBag, transport: TrainFront, bills: Home, salary: Wallet };
const categoryColors: Record<string, string> = { food: 'mint', shopping: 'peach', transport: 'blue', bills: 'yellow', salary: 'mint' };
const navigation = [{ label: 'Home', icon: Home }, { label: 'Plans', icon: CalendarDays }, { label: 'Activity', icon: ArrowLeftRight }, { label: 'Reports', icon: ChartNoAxesCombined }, { label: 'Settings', icon: Settings }];
type Modal = { kind: 'transaction'; type: 'expense' | 'income'; occurrence?: Occurrence } | { kind: 'link'; occurrence: Occurrence } | { kind: 'skip'; occurrence: Occurrence } | { kind: 'reports' } | { kind: 'profile' } | { kind: 'settings' };

function IconBubble({ icon: Icon, color = 'mint' }: { icon: LucideIcon; color?: string }) { return <span className={`icon-bubble ${color}`}><Icon size={20} strokeWidth={1.7} aria-hidden="true"/></span>; }
function Section({ title, aside, children, id, className = '' }: { title: string; aside?: ReactNode; children: ReactNode; id?: string; className?: string }) { return <section className={`surface section ${className}`} id={id}><div className="section-heading"><h2>{title}</h2>{aside}</div>{children}</section>; }
function ModalFrame({ title, close, children }: { title: string; close: () => void; children: ReactNode }) {
  const dialog = useRef<HTMLDialogElement>(null);
  useEffect(() => { const target = dialog.current; target?.showModal(); return () => target?.close(); }, []);
  return <dialog ref={dialog} className="preview-dialog" aria-labelledby="dialog-title" onCancel={e => { e.preventDefault(); close(); }} onClick={e => { if (e.target === e.currentTarget) { const box = e.currentTarget.getBoundingClientRect(); if (e.clientX < box.left || e.clientX > box.right || e.clientY < box.top || e.clientY > box.bottom) close(); } }}><div className="dialog-header"><h2 id="dialog-title">{title}</h2><button className="icon-button" onClick={close} aria-label="Close dialog"><X size={20}/></button></div><p className="dialog-note">Sample data only. Changes stay in this preview until you reset or reload it.</p>{children}</dialog>;
}

function TransactionForm({ records, modal, save, close }: { records: Document[]; modal: Extract<Modal, { kind: 'transaction' }>; save: (docs: Document[]) => void; close: () => void }) {
  const [type, setType] = useState(modal.type);
  const [amount, setAmount] = useState(modal.occurrence ? String(n(modal.occurrence.data, 'amount') / 100) : '');
  const [categoryId, setCategoryId] = useState(modal.occurrence ? s(modal.occurrence.data, 'categoryId') : '');
  const [method, setMethod] = useState('upi');
  const [recordDate, setRecordDate] = useState(previewToday);
  const [note, setNote] = useState(modal.occurrence ? s(modal.occurrence.data, 'name') : '');
  const [error, setError] = useState('');
  const [alreadySpent, setAlreadySpent] = useState(false);
  const amountInPaise = Math.round(Number(amount) * 100);
  const allowance = checkSpending(records, previewToday, amountInPaise, categoryId);
  function submit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault(); setError('');
    try {
      if (recordDate > previewToday) throw new Error('Use a plan for future income or expenses.');
      if (type === 'expense' && !modal.occurrence && !alreadySpent && !allowance.allowed) throw new Error(`Above your spending allowance by ${money(allowance.shortfall)}. Choose Already spent to record an actual expense.`);
      const data = validateData('transaction', { type, amount: amountInPaise, categoryId, paymentMethodId: method, date: recordDate, description: note, ...(modal.occurrence ? { occurrenceId: modal.occurrence.id } : {}) });
      const docs = [document(crypto.randomUUID(), 'transaction', data)];
      if (modal.occurrence) docs.push(document(modal.occurrence.id, 'occurrence', modal.occurrence.data));
      save(docs); close();
    } catch (err) { setError(err instanceof Error ? err.message : 'Could not save. Please try again.'); }
  }
  return <form onSubmit={submit} className="transaction-form"><div className="type-toggle"><button type="button" aria-pressed={type === 'expense'} onClick={() => { setType('expense'); setCategoryId(''); }}><ArrowUpRight size={18}/>Expense</button><button type="button" aria-pressed={type === 'income'} onClick={() => { setType('income'); setCategoryId(''); }}><ArrowDownLeft size={18}/>Income</button></div><label>Amount (₹)<input type="number" inputMode="decimal" min="0.01" step="0.01" required placeholder="0.00" value={amount} onChange={e => setAmount(e.target.value)}/></label><div className="form-pair"><label>Category<select required value={categoryId} onChange={e => setCategoryId(e.target.value)}><option value="">Choose category</option>{records.filter(r => !r.deleted && r.kind === 'category' && s(r.data, 'type') === type).map(r => <option key={r.id} value={r.id}>{s(r.data, 'name')}</option>)}</select></label><label>Payment method<select value={method} onChange={e => setMethod(e.target.value)}>{records.filter(r => r.kind === 'paymentMethod').map(r => <option key={r.id} value={r.id}>{s(r.data, 'name')}</option>)}</select></label></div><label>Date<input type="date" required value={recordDate} onChange={e => setRecordDate(e.target.value)}/></label><label><span>Note <span className="optional">optional</span></span><input value={note} onChange={e => setNote(e.target.value)} placeholder="What was it for?" maxLength={1000}/></label>{type === 'expense' && !modal.occurrence && <div className="form-allowance">Category allowance <strong>{money(allowance.maximum)}</strong><label className="checkbox"><input type="checkbox" checked={alreadySpent} onChange={e => setAlreadySpent(e.target.checked)}/>Already spent — record the actual expense</label></div>}{error && <p className="form-error" role="alert">{error}</p>}<div className="dialog-footer"><button className="primary-button" type="submit">Save transaction<Check size={18}/></button><button className="quiet-button" type="button" onClick={close}>Cancel</button></div></form>;
}

function Overview() {
  const [records, setRecords] = useState(sampleRecords);
  const [modal, setModal] = useState<Modal | null>(null);
  const [notice, setNotice] = useState('');
  const [more, setMore] = useState('');
  const [linkId, setLinkId] = useState('');
  const [showAllActivity, setShowAllActivity] = useState(false);
  const [spendAmount, setSpendAmount] = useState('');
  const [spendCategory, setSpendCategory] = useState('food');
  const [hideMoney, setHideMoney] = useState(false);
  const totals = summary(records, previewToday);
  const fullSchedule = occurrences(records, previewToday, '2100-12-31');
  const payments = nextPaymentPerPlan(fullSchedule);
  const labels = new Map(records.filter(r => !r.deleted).map(r => [r.id, s(r.data, 'name')]));
  const transactions = records.filter(r => !r.deleted && r.kind === 'transaction').sort((a, b) => s(b.data, 'date').localeCompare(s(a.data, 'date')));
  const spend = checkSpending(records, previewToday, Math.round(Number(spendAmount) * 100), spendCategory);
  const save = (docs: Document[]) => { setRecords(previous => [...previous.filter(r => !docs.some(d => d.id === r.id)), ...docs]); setNotice('Saved in the sample ledger'); setMore(''); };
  const close = () => setModal(null);
  function goTo(target: string) { documentElement(target)?.scrollIntoView({ behavior: matchMedia('(prefers-reduced-motion: reduce)').matches ? 'instant' : 'smooth', block: 'start' }); }
  function navigate(label: string) { if (label === 'Home') window.scrollTo({ top: 0, behavior: 'smooth' }); else if (label === 'Plans') goTo('payments'); else if (label === 'Activity') goTo('activity'); else if (label === 'Reports') setModal({ kind: 'reports' }); else setModal({ kind: 'settings' }); }
  useEffect(() => { if (!notice) return; const timer = setTimeout(() => setNotice(''), 4000); return () => clearTimeout(timer); }, [notice]);
  const currency = (amount: number) => hideMoney ? '••••••' : money(amount);
  return <>
    <div className="preview-banner"><span>DESIGN PREVIEW</span><span className="banner-dot"/>Sample data · 7 Oct 2026<button onClick={() => { setRecords(sampleRecords); setNotice('Sample ledger reset'); }} aria-label="Reset sample data"><RotateCcw size={13}/><span>Reset</span></button></div>
    <a className="skip-link" href="#overview">Skip to overview</a>
    <header className="app-header"><a className="brand" href="#overview"><span className="brand-mark"><Wallet size={22} strokeWidth={1.7}/></span>FinTrack<span className="brand-dot">.</span></a><nav className="desktop-nav" aria-label="Main navigation">{navigation.map(item => <button key={item.label} aria-current={item.label === 'Home' ? 'page' : undefined} onClick={() => navigate(item.label)}>{item.label}</button>)}</nav><div className="header-end"><span className="sync-state"><span/>Sample ledger</span><button className="avatar" aria-label="Sample account profile" onClick={() => setModal({ kind: 'profile' })}>{previewName.charAt(0)}</button></div></header>

    <main id="overview" className="overview"><div className="welcome"><div><p className="eyebrow">A LITTLE CLARITY, EVERY DAY</p><h1>Hello, {previewName}<span className="greeting-dot">.</span></h1><p>Let’s make room for what matters.</p></div><div className="view-pills" aria-label="Overview shortcuts"><button aria-current="page">Overview</button><button onClick={() => goTo('budgets')}>Budgets</button></div></div>
      <div className="overview-grid"><div className="money-column">
        <section className="balance-card" aria-label="Available credit"><div className="balance-top"><span>Available credit</span><button className="balance-menu" aria-label={hideMoney ? 'Show balances' : 'Hide balances'} onClick={() => setHideMoney(v => !v)}><MoreHorizontal size={22}/></button></div><div className="balance-amount">{currency(totals.unallocated)}<span>INR</span></div><p>After bills, savings & category reserves</p><div className="balance-bottom"><span><CalendarDays size={15}/>1 – 31 October 2026</span><span className="balance-tag"><ShieldCheck size={14}/>Planned, not guessed</span></div></section>
        <div className="quick-actions" aria-label="Quick actions">{[{ label: 'Expense', icon: ArrowUpRight, color: 'peach', action: () => setModal({ kind: 'transaction', type: 'expense' }) }, { label: 'Income', icon: ArrowDownLeft, color: 'mint', action: () => setModal({ kind: 'transaction', type: 'income' }) }, { label: 'Plans', icon: CalendarDays, color: 'yellow', action: () => goTo('payments') }, { label: 'Reports', icon: ChartNoAxesCombined, color: 'blue', action: () => setModal({ kind: 'reports' }) }].map(item => <button key={item.label} onClick={item.action}><IconBubble icon={item.icon} color={item.color}/><span>{item.label}</span></button>)}</div>
        <section className="surface supporting-totals" aria-label="Balance breakdown">{[{ label: 'Current balance', value: totals.balance, icon: Wallet, color: 'mint' }, { label: 'Bills reserved', value: totals.commitments, icon: CalendarDays, color: 'peach' }, { label: 'Protected savings', value: totals.savings, icon: ShieldCheck, color: 'yellow' }].map(item => <div key={item.label}><span className={`total-dot ${item.color}`}><item.icon size={14}/></span><span className="total-label">{item.label}</span><strong>{currency(item.value)}</strong></div>)}</section>
        <Section title="Next payments" id="payments" className="payments-panel" aside={<span className="section-count">{payments.length} plans</span>}><p className="section-description">Just the next unpaid payment for each plan.</p>{payments.length ? <div className="payment-list">{payments.map(payment => { const planId = s(payment.data, 'planId'); const Icon = planId === 'internet' ? Wifi : planId === 'streaming' ? Clapperboard : categoryIcons[s(payment.data, 'categoryId')] ?? CalendarDays; const color = payment.state === 'overdue' ? 'peach' : payment.state === 'due' ? 'yellow' : categoryColors[s(payment.data, 'categoryId')] ?? 'mint'; return <article className="payment-row" key={payment.id}><div className="payment-main"><IconBubble icon={Icon} color={color}/><div className="row-copy"><h3>{s(payment.data, 'name')}</h3><p>{date(s(payment.data, 'date'))}<span className={`status-tag ${payment.state}`}>{payment.state === 'due' ? 'Due today' : payment.state === 'overdue' ? 'Overdue' : 'Upcoming'}</span></p></div><strong className="row-amount">{currency(n(payment.data, 'amount'))}</strong></div><div className="payment-actions"><button className="payment-primary" onClick={() => setModal({ kind: 'transaction', type: s(payment.data, 'type') as 'income' | 'expense', occurrence: payment })}>{s(payment.data, 'type') === 'income' ? 'Received' : 'Mark paid'}<ArrowRight size={13}/></button><button className="row-more" aria-label={`More actions for ${s(payment.data, 'name')}`} aria-expanded={more === payment.id} onClick={() => setMore(value => value === payment.id ? '' : payment.id)}><MoreHorizontal size={19}/></button>{more === payment.id && <div className="payment-extra"><button onClick={() => { setLinkId(''); setMore(''); setModal({ kind: 'link', occurrence: payment }); }}><Link2 size={15}/>Link transaction</button><button onClick={() => { setMore(''); setModal({ kind: 'skip', occurrence: payment }); }}><SkipForward size={15}/>Skip this payment</button></div>}</div></article>; })}</div> : <div className="empty-state"><CircleCheck size={25}/><p>You’re all caught up.</p><span>No unpaid payments in the sample schedule.</span></div>}</Section>
      </div><div className="detail-column">
        <Section title="Your budgets" id="budgets" aside={<span className="section-period">THIS CYCLE</span>}><p className="section-description">Small limits. A little more breathing room.</p><div className="budgets-list">{totals.budgets.map(budget => { const percent = Math.min(100, budget.amount ? budget.spent / budget.amount * 100 : 0); const color = categoryColors[budget.categoryId] ?? 'mint'; return <div className="budget-row" key={budget.id}><div className="budget-heading"><IconBubble icon={categoryIcons[budget.categoryId] ?? Wallet} color={color}/><div className="row-copy"><h3>{labels.get(budget.categoryId)}</h3><p>{currency(budget.remaining)} left to spend</p></div><div className="budget-figures"><strong>{currency(budget.spent)}</strong><span>of {currency(budget.amount)}</span></div></div><div className="budget-track" role="meter" aria-label={`${labels.get(budget.categoryId)} budget used`} aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(percent)} aria-valuetext={`${money(budget.spent)} of ${money(budget.amount)}`}><span className={color} style={{ width: `${percent}%` }}/></div></div>; })}</div></Section>
        <Section title="Recent activity" id="activity" aside={<button className="section-link" onClick={() => setShowAllActivity(value => !value)}>{showAllActivity ? 'Show less' : 'View all'}<ArrowUpRight size={14}/></button>}><div className="activity-list">{transactions.slice(0, showAllActivity ? transactions.length : 4).map(transaction => { const income = s(transaction.data, 'type') === 'income'; const categoryId = s(transaction.data, 'categoryId'); const Icon = s(transaction.data, 'description').toLowerCase().includes('coffee') ? Coffee : categoryIcons[categoryId] ?? Wallet; return <article className="activity-row" key={transaction.id}><IconBubble icon={Icon} color={categoryColors[categoryId]}/><div className="row-copy"><h3>{s(transaction.data, 'description') || labels.get(categoryId)}</h3><p>{labels.get(s(transaction.data, 'paymentMethodId'))} · {date(s(transaction.data, 'date'))}</p></div><strong className={`row-amount ${income ? 'income' : ''}`}>{income ? '+' : '−'}{currency(n(transaction.data, 'amount'))}</strong></article>; })}</div></Section>
        <details className="spend-check surface"><summary><IconBubble icon={ShieldCheck} color="mint"/><span><strong>Can I spend this?</strong><small>Check before you checkout.</small></span><ChevronDown size={19}/></summary><div className="spend-body"><div className="form-pair"><label>Amount (₹)<input type="number" min="0.01" step="0.01" inputMode="decimal" placeholder="0.00" value={spendAmount} onChange={e => setSpendAmount(e.target.value)}/></label><label>Category<select value={spendCategory} onChange={e => setSpendCategory(e.target.value)}>{records.filter(r => r.kind === 'category' && s(r.data, 'type') === 'expense').map(r => <option key={r.id} value={r.id}>{s(r.data, 'name')}</option>)}</select></label></div><p>Available for this category <strong>{currency(spend.maximum)}</strong></p>{Number(spendAmount) > 0 && <p role="status" className={spend.allowed ? 'income' : 'form-error'}>{spend.allowed ? 'Within your spending allowance' : `Over your allowance by ${money(spend.shortfall)}`}</p>}<small>Uses recorded money after bills, savings and other category reserves. Expected income is excluded.</small></div></details>
        <p className="footnote"><ShieldCheck size={13}/>Thoughtful planning. A calmer month.</p>
      </div></div>
    </main>
    <button className="add-transaction" aria-label="Add transaction" title="Add transaction" onClick={() => setModal({ kind: 'transaction', type: 'expense' })}><Plus size={21}/><span>Add transaction</span></button>
    <nav className="bottom-dock" aria-label="Mobile navigation">{navigation.map(item => <button key={item.label} aria-current={item.label === 'Home' ? 'page' : undefined} onClick={() => navigate(item.label)}><item.icon size={20} strokeWidth={1.7}/><span>{item.label}</span></button>)}</nav>
    {notice && <div className="toast" role="status"><CircleCheck size={18}/>{notice}<button className="icon-button" aria-label="Dismiss message" onClick={() => setNotice('')}><X size={16}/></button></div>}
    {modal && <ModalFrame title={modal.kind === 'transaction' ? modal.occurrence ? 'Record payment' : 'Add transaction' : modal.kind === 'link' ? 'Link transaction' : modal.kind === 'skip' ? 'Skip this payment?' : modal.kind === 'reports' ? 'This cycle, at a glance' : modal.kind === 'profile' ? 'Your FinTrack' : 'Preview settings'} close={close}>
      {modal.kind === 'transaction' && <TransactionForm records={records} modal={modal} save={save} close={close}/>}
      {modal.kind === 'skip' && <><p className="modal-paragraph">Skip {s(modal.occurrence.data, 'name')} for {date(s(modal.occurrence.data, 'date'))}? Its reservation will be released, and this preview will show the next unpaid occurrence.</p><div className="dialog-footer"><button className="primary-button" onClick={() => { save([document(modal.occurrence.id, 'occurrence', { ...modal.occurrence.data, status: 'skipped' })]); close(); }}>Skip payment</button><button className="quiet-button" onClick={close}>Cancel</button></div></>}
      {modal.kind === 'link' && <><label className="link-label">Existing transaction<select value={linkId} onChange={e => setLinkId(e.target.value)}><option value="">Choose a transaction</option>{transactions.filter(t => !s(t.data, 'occurrenceId') && s(t.data, 'type') === s(modal.occurrence.data, 'type')).map(t => <option key={t.id} value={t.id}>{s(t.data, 'description') || s(t.data, 'category')} · {money(n(t.data, 'amount'))} · {date(s(t.data, 'date'))}</option>)}</select></label><div className="dialog-footer"><button className="primary-button" disabled={!linkId} onClick={() => { const transaction = transactions.find(t => t.id === linkId); if (!transaction) return; save([document(modal.occurrence.id, 'occurrence', modal.occurrence.data), { ...transaction, data: { ...transaction.data, occurrenceId: modal.occurrence.id } }]); close(); }}>Link payment</button><button className="quiet-button" onClick={close}>Cancel</button></div></>}
      {modal.kind === 'reports' && <div className="report-summary"><p>1 – 31 October 2026 · INR</p>{[{ label: 'Income', amount: totals.income, color: 'mint' }, { label: 'Expenses', amount: totals.expenses, color: 'peach' }, { label: 'Net this cycle', amount: totals.income - totals.expenses, color: 'yellow' }].map(item => <div key={item.label} className={item.color}><span>{item.label}</span><strong>{money(item.amount)}</strong></div>)}<p className="dialog-note">Calculated from the sample ledger with FinTrack’s existing financial engine.</p></div>}
      {modal.kind === 'profile' && <div className="profile-preview"><span className="avatar">A</span><h3>{previewName} · Sample account</h3><p>Overview design preview</p><button className="primary-button" onClick={close}>Back to overview</button></div>}
      {modal.kind === 'settings' && <div className="settings-preview"><p>This isolated preview uses INR, a monthly payday of 1, and {money(800000)} in protected savings. Your actual account settings are separate.</p><button className="primary-button" onClick={() => { setRecords(sampleRecords); setNotice('Sample ledger reset'); close(); }}><RotateCcw size={17}/>Reset sample ledger</button></div>}
    </ModalFrame>}
  </>;
}
function documentElement(id: string) { return window.document.getElementById(id); }
createRoot(window.document.getElementById('root')!).render(<Overview/>);
